image: python:3.9.9

stages:
  - test

test:
  stage: test
  rules:
    - changes:
        - README.md
      when: never
  script:
    - python -m pip install -U pip
    - pip install -r requirements.txt
    - pytest
