name: tests

on:
  push:
    branches:    
      - 'develop'
    paths-ignore:
      - 'README.md'
      - 'docker-compose*.yml'
      - 'Dockerfile'
      - '/.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./tests/sql_app.db
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
